_base_ = [
    "../backbones/dinov2_reg_small.py",
]
model = dict(
    backbone=dict(
        layers_to_extract=1,
    ),
    decode_head=dict(
        type="DualDecodeHead",
        dir_head=dict(
            type="LinearDirectionHead",
            in_channels=384,
            channels=384,
            dropout_ratio=0,
            gt_scale_factor=1.0,
            align_corners=False,
            loss_decode=[
                dict(
                    loss_name="loss_dir",
                    type="EfficientDirectionalLoss",
                    div=180,
                    pad=10,
                    squish_values=True,
                    norm_values=True,
                    norm_order=1,
                    mask_patches=True,
                    patch_thr=0.98,
                    loss_weight=1,
                    kernel_cfg=dict(
                        type="radial_line_kernel",
                    ),
                ),
            ],
        ),
        seg_head=dict(
            type="LinearHead",
            num_classes=1,
            in_channels=384,
            channels=384,
            dropout_ratio=0,
            align_corners=False,
            loss_decode=dict(
                loss_weight=1.0,
                type="CrossEntropyLoss",
                use_sigmoid=True,
            ),
        ),
    ),
)
